<?php

$plugin_cf['xhshop']['shop_published']="@PUBLISHED@";
$plugin_cf['xhshop']['shop_token']="";
$plugin_cf['xhshop']['shop_minimum_order']="20.00";
$plugin_cf['xhshop']['shop_default_currency']="€";
$plugin_cf['xhshop']['shop_currency_code']="EUR";
$plugin_cf['xhshop']['shop_image_folder']="shop/";
$plugin_cf['xhshop']['shop_preview_folder']="shop/";
$plugin_cf['xhshop']['shop_image_extensions']="jpeg, jpg, gif, png, svg, tif, tiff";
$plugin_cf['xhshop']['contact_order_email']="";
$plugin_cf['xhshop']['contact_company_name']="XH-Shop DEMO";
$plugin_cf['xhshop']['contact_name']="XH-Shop Team";
$plugin_cf['xhshop']['contact_street']="XH Str. 1.7";
$plugin_cf['xhshop']['contact_zip_code']="12345";
$plugin_cf['xhshop']['contact_city']="Simpleburg/XH";
$plugin_cf['xhshop']['taxes_vat_full']="19";
$plugin_cf['xhshop']['taxes_vat_reduced']="7";
$plugin_cf['xhshop']['taxes_vat_default_full']="true";
$plugin_cf['xhshop']['taxes_dont_deal_with_taxes']="";
$plugin_cf['xhshop']['shipping_charge_for_shipping']="true";
$plugin_cf['xhshop']['shipping_forwarding_expenses_up_to']="50.00";
$plugin_cf['xhshop']['shipping_forwarding_expenses']="DE: 1=4.50; 3= 6.25; 6= 9.75; 24.00\nAT: 1=9.00; 3=12.50; 6=19.50; 48.00\nCH: 1=9.00; 3=12.50; 6=19.50; 48.00\nFR: 1=9.00; 3=12.50; 6=19.50; 48.00\n";
$plugin_cf['xhshop']['shipping_shipping_up_to']="true";
$plugin_cf['xhshop']['cash-in-advance_is_active']="true";
$plugin_cf['xhshop']['cash-in-advance_fee']="-3.00";
$plugin_cf['xhshop']['cash-on-delivery_is_active']="true";
$plugin_cf['xhshop']['cash-on-delivery_fee']="9.95";
$plugin_cf['xhshop']['on-account_is_active']="true";
$plugin_cf['xhshop']['on-account_fee']="5.00";
$plugin_cf['xhshop']['paypal_is_active']="true";
$plugin_cf['xhshop']['paypal_fee']="0.00";
$plugin_cf['xhshop']['paypal_email']="";
$plugin_cf['xhshop']['paypal_sandbox']="true";
$plugin_cf['xhshop']['categories_use_categories']="true";
$plugin_cf['xhshop']['categories_allow_show_all']="true";
